apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  labels:
    run: $APP_NAME
spec:
  type: LoadBalancer
  ports:
  - port: $PORT
    targetPort: 8080
    protocol: TCP
  selector:
    run: $APP_NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: gcr.io/kubernetes-kata/$APP_NAME:$VERSION
        ports:
        - containerPort: 8080